### ISSUE TITLE
Disk Image - Add applications and configuration

### ISSUE THREAD

**Issue by greygoo** [Radio-Meshnet/disk-image#1]
# Description
Currently images are customized using a bunch of bash scripts.
To make it easier to maintain and be able to also run it on a booted system local as well as via ssh, create ansible receipts from the bash scripts for the existing scripts and new ones for new tasks

Make sure that configuration for different tasks can be installed based on the configured board and branding. Create a global config file for these variables.

This issue is an epic for collecting all related tasks:

# Tasks
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] #7
- [ ] #8
- [ ] Add script to restore the system
- [ ] #12
- [ ] Add script to create btrfs backup snapshot from user home
- [ ] Create system updater that creates snapshot before updating
- [ ] Create script to rollback update done with the system updater
- [ ] #9
- [ ] #10
- [ ] Install Kommunikator - application and config for default user
- [ ] Install distribution group - application and config for default user
- [ ] Install nexus - application and config for default user
- [ ] Install upspack - application and config
- [ ] Install branding - media files for default user
- [ ] Install branding - media files for system
- [ ] Install Desktop config for default user
- [ ] Install x11vnc - application and config
- [ ] #11
- [ ] Install uart3overlay file for bananapi boards
- [ ] Create AP config for USB wifi adapter
- [ ] Install soundmodem - application and config
- [ ] Install direwolf - application and config for user
- [ ] Add simple web interface served via the AP network for configuring the system as client in a WiFi net
- [ ] Create update_system.sh that updates the OS as well as additional Radio-Meshnet software
